name: employee-management-system
services:
  postgres:
    container_name: postgres_ems
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@321
      POSTGRES_DB: demo_ems
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
  ems:
    container_name: ems
    build: .
    image: ems:0.0.1
    ports:
      - "8085:8082"
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres-ems-data
