spring:
  application:
    name: 02-employee-management-system
  datasource:
    url: jdbc:postgresql://postgres:5432/demo_ems
    username: admin
    password: admin@321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: admin
    password: admin@321

server:
  port: 8082
